name=LTR329ALSOpticalSensor
version=0.0.0
author=mumanchu
maintainer=mumanchu <info@muman.ch>
sentence=Arduino Library for LTR-329ALS-01 Optical Sensor
paragraph=With I2C interface
category=Sensors
includes=LTR329ALSOpticalSensor.h
url=https://github.com/mumanchu/LTR329ALSOpticalSensor
architectures=*
